### ISSUE TITLE
what if i told you

### ISSUE THREAD

**Issue by TechDudie** [Hardwaregore/GrassBandits#4]
neither of us acutally changed the password 🤦🏻‍♂️ i just logged on

**Comment by TechDudie** [comment]
![0187B60A-2844-4BBB-A586-244C2DC9D1F1](https://user-images.githubusercontent.com/73961295/167026895-39d60d0a-c9bb-4c96-a489-62358d0a625f.png)

**Comment by TechDudie** [comment]
dont believe me? look at date

**Comment by Hardwaregore** [comment]
Imagine dragons I submitted a help ticket to linode during my time at the ibiry?🤯

**Comment by Hardwaregore** [comment]
@TechDudie

**Comment by Hardwaregore** [comment]
They had me backup the linode and they wiped da drive. id10+

**Comment by TechDudie** [comment]
🤯

**Comment by TechDudie** [comment]
🤯🤯🤯🤯

**Comment by TechDudie** [comment]
🤯🤯🤯🤯🤯🤯🤯🤯

**Comment by TechDudie** [comment]
https://github.com/TechDudie/grassbandits
https://techdude.pythonanywhere.com
