### ISSUE TITLE
messy

### ISSUE THREAD

**Issue by TechDudie** [Hardwaregore/GrassBandits#5]
messy very messy
i have 2 folders, static and dynamic
and app.py is in the root directory

simple and clean

**Comment by SirAlexBigBrain** [comment]
Who asked you? ?php?

**Comment by TechDudie** [comment]
you misspeeled the php tag 🤦🏻‍♂️ iD10+

**Comment by TechDudie** [comment]
you heard the ?php? from chinny and he didnt even say it correctly its his fault he taught u wrong

**Comment by SirAlexBigBrain** [comment]
Whoops. I am your humble servant, master.

**Comment by Hardwaregore** [comment]
Who cares <?php ?>
